CREATE TABLE IF NOT EXISTS purchases (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL,
  purchase_order_id INT(11) NULL,
  provider_id INT(11) NOT NULL,
  invoice_number VARCHAR(100) NOT NULL,
  invoice_date DATE NOT NULL,
  due_date DATE NULL,
  payment_date DATE NULL,
  status ENUM('pending','partial','paid','overdue','cancelled') DEFAULT 'pending',
  payment_method VARCHAR(50) NULL,
  subtotal DECIMAL(15,2) DEFAULT 0.00,
  tax DECIMAL(15,2) DEFAULT 0.00,
  total DECIMAL(15,2) DEFAULT 0.00,
  paid_amount DECIMAL(15,2) DEFAULT 0.00,
  balance DECIMAL(15,2) DEFAULT 0.00,
  notes TEXT NULL,
  xml_file VARCHAR(255) NULL,
  pdf_file VARCHAR(255) NULL,
  created_by INT(11) NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  deleted_at DATETIME NULL,
  INDEX idx_code (code),
  INDEX idx_purchase_order_id (purchase_order_id),
  INDEX idx_provider_id (provider_id),
  INDEX idx_invoice_number (invoice_number),
  INDEX idx_status (status),
  INDEX idx_invoice_date (invoice_date),
  INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
