CREATE TABLE IF NOT EXISTS purchase_orders (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL,
  provider_id INT(11) NOT NULL,
  order_date DATE NOT NULL,
  delivery_date DATE NULL,
  status ENUM('draft','pending','approved','rejected','received','cancelled') DEFAULT 'draft',
  type ENUM('inventory','usage','service') DEFAULT 'inventory',
  subtotal DECIMAL(15,2) DEFAULT 0.00,
  tax DECIMAL(15,2) DEFAULT 0.00,
  total DECIMAL(15,2) DEFAULT 0.00,
  notes TEXT NULL,
  approved_by INT(11) NULL,
  approved_at DATETIME NULL,
  rejected_by INT(11) NULL,
  rejected_at DATETIME NULL,
  rejection_reason TEXT NULL,
  received_by INT(11) NULL,
  received_at DATETIME NULL,
  created_by INT(11) NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  deleted_at DATETIME NULL,
  INDEX idx_code (code),
  INDEX idx_provider_id (provider_id),
  INDEX idx_status (status),
  INDEX idx_type (type),
  INDEX idx_order_date (order_date),
  INDEX idx_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS purchase_order_items (
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  purchase_order_id INT(11) NOT NULL,
  product_id INT(11) NULL,
  item_type ENUM('product','service','custom') DEFAULT 'product',
  description VARCHAR(255) NOT NULL,
  quantity DECIMAL(10,2) DEFAULT 1.00,
  unit_price DECIMAL(15,2) DEFAULT 0.00,
  tax_rate DECIMAL(5,2) DEFAULT 0.00,
  subtotal DECIMAL(15,2) DEFAULT 0.00,
  tax_amount DECIMAL(15,2) DEFAULT 0.00,
  total DECIMAL(15,2) DEFAULT 0.00,
  notes TEXT NULL,
  INDEX idx_purchase_order_id (purchase_order_id),
  INDEX idx_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
